version: '3'

services:

  webserver:
    image: myapa
    restart: always
    networks:
      - mynet
    ports:
      - 8080:80
    depends_on:
      - mydb

  mydb:
    image: mariadb
    networks:
      - mynet
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - prj1vol:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8083:80
    networks:
      - mynet
    links:
      - "mydb:db"

networks:
   mynet:

volumes:
   prj1vol:
     driver: local
