version: '3'

services:

  webserver:
    image: myapa
    networks:
      - mynet
    ports:
      - 8080:80
    depends_on:
      - db
      
  mydb:
    image: mariadb
    networks:
      - mynet
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    networks:
      - mynet
    links:
      - "mydb:db"
      
  networks:
    mynet
