version: '3'

services:

  webserver:
    image: myapa
    restart: always
    networks:
      - mynet
    ports:
      - 8080:80
    depends_on:
      - mydb

  mydb:
    image: mariadb
    networks:
      - mynet
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    networks:
      - mynet
    links:
      - "mydb:db"

networks:
   mynet:
